FROM coturn/coturn:4.6.3

ENV TURN_REALM=chat.coolify.hesamian.com \
    TURN_MIN_PORT=49160 \
    TURN_MAX_PORT=49200

EXPOSE 3478/tcp 3478/udp 49160-49200/udp

ENTRYPOINT ["/bin/sh", "-ec"]
CMD [": \"${TURN_SECRET:?TURN_SECRET must be set}\"; : \"${TURN_EXTERNAL_IP:?TURN_EXTERNAL_IP must be set}\"; exec turnserver --no-cli --fingerprint --use-auth-secret --static-auth-secret=\"$TURN_SECRET\" --realm=\"$TURN_REALM\" --external-ip=\"$TURN_EXTERNAL_IP\" --listening-port=3478 --min-port=\"$TURN_MIN_PORT\" --max-port=\"$TURN_MAX_PORT\" --log-file=stdout"]
